# Pendahuluan Numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

# Membuat Array

In [12]:
a = np.array ([2, 3, 4])
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int32')

In [14]:
b = np.array([1.2, 3.5, 5.11])

In [15]:
b.dtype

dtype('float64')

In [17]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
c = np.array([ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
np.empty( (2,3) )

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
np.arange(10,30,5 )

array([10, 15, 20, 25])

In [23]:
np.arange(0,2,0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [24]:
from numpy import pi

In [25]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
x = np.linspace(0,2*pi,100 )

In [27]:
f = np.sin(x)

# Menampilkan Array

In [29]:
a = np.arange(6)

In [30]:
print(a)

[0 1 2 3 4 5]


In [31]:
b = np.arange(12).reshape(4,3)

In [32]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [33]:
c = np.arange(24).reshape(2,3,4)

In [34]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [35]:
print(np.arange(10000) )

[   0    1    2 ... 9997 9998 9999]


In [36]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


# Operasi Dasar Numpy

In [3]:
import numpy as np

In [4]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [5]:
c = a-b
c

array([20, 29, 38, 47])

In [6]:
b**2

array([0, 1, 4, 9])

In [7]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [8]:
a<35

array([ True,  True, False, False])

In [9]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A*B

array([[2, 0],
       [0, 4]])

In [10]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [11]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [12]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [13]:
b += a
b

array([[3.75880748, 3.76856318, 3.3189693 ],
       [3.13907238, 3.93909326, 3.52118497]])

In [18]:
a = np.random.random((2,3))
a

array([[0.69219797, 0.88190664, 0.25394013],
       [0.11154789, 0.35225272, 0.97172703]])

In [19]:
a.sum()

3.2635723862480055

In [20]:
a.min()

0.11154789377782848

In [21]:
a.max()

0.9717270299120941

In [22]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [25]:
b.min(axis=1)

array([0, 4, 8])

In [26]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Fungsi Universal

In [27]:
B = np.arange(3)
B

array([0, 1, 2])

In [28]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [29]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [30]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

# Modifikasi dan Manipulasi Array

# Inxeing, Slicing, dan Iterating

In [31]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [32]:
a[2]

8

In [33]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [35]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [36]:
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [37]:
for i in a:
    print(i**(1/3))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\ASUS\AppData\Local\Temp\ipykernel_6804\1047892610.py:2: RuntimeWarning: invalid value encountered in power
  print(i**(1/3))


In [38]:
def f(x,y):
    return 10*x+y

In [39]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [40]:
b[2,3]

23

In [41]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [42]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [43]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [44]:
b[-1]

array([40, 41, 42, 43])

In [47]:
c = np.array( [[[ 0, 1, 2],
                [10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c.shape

(2, 2, 3)

In [48]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [49]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [50]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [51]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Manipulasi Bentuk

# Mengubah bentuk sebuah array

In [52]:
a = np.floor(10*np.random.random((3,4)))
a

array([[5., 0., 4., 0.],
       [9., 2., 7., 9.],
       [7., 0., 9., 6.]])

In [53]:
a.shape

(3, 4)

In [54]:
a.ravel()

array([5., 0., 4., 0., 9., 2., 7., 9., 7., 0., 9., 6.])

In [55]:
a.reshape(6,2)

array([[5., 0.],
       [4., 0.],
       [9., 2.],
       [7., 9.],
       [7., 0.],
       [9., 6.]])

In [56]:
a.T

array([[5., 9., 7.],
       [0., 2., 0.],
       [4., 7., 9.],
       [0., 9., 6.]])

In [57]:
a.T.shape

(4, 3)

In [58]:
a.shape

(3, 4)

In [59]:
a

array([[5., 0., 4., 0.],
       [9., 2., 7., 9.],
       [7., 0., 9., 6.]])

In [60]:
a.resize((2,6))
a

array([[5., 0., 4., 0., 9., 2.],
       [7., 9., 7., 0., 9., 6.]])

In [61]:
a.reshape(3,-1)

array([[5., 0., 4., 0.],
       [9., 2., 7., 9.],
       [7., 0., 9., 6.]])

In [62]:
a = np.floor(10*np.random.random((2,2)))
a

array([[9., 9.],
       [8., 9.]])

In [65]:
b = np.floor(10*np.random.random((2,2)))
b

array([[3., 1.],
       [6., 3.]])

In [66]:
np.vstack((a,b))

array([[9., 9.],
       [8., 9.],
       [3., 1.],
       [6., 3.]])

In [67]:
np.hstack((a,b))

array([[9., 9., 3., 1.],
       [8., 9., 6., 3.]])

In [68]:
from numpy import newaxis
np.column_stack((a,b))

array([[9., 9., 3., 1.],
       [8., 9., 6., 3.]])

In [69]:
a = np.array([4.,2.])
b = np.array([2.,8.])
a[:,newaxis]

array([[4.],
       [2.]])

In [70]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 2.],
       [2., 8.]])

In [71]:
np.vstack((a[:,newaxis],b[:,newaxis]))

array([[4.],
       [2.],
       [2.],
       [8.]])

In [72]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

# Memecah array menjadi beberapa bagian yang lebih kecil

In [73]:
a = np.floor(10*np.random.random((2,12)))
a

array([[5., 6., 8., 6., 1., 8., 4., 8., 4., 7., 8., 3.],
       [6., 6., 3., 8., 4., 7., 9., 2., 5., 3., 2., 2.]])

In [74]:
np.hsplit(a,3)

[array([[5., 6., 8., 6.],
        [6., 6., 3., 8.]]),
 array([[1., 8., 4., 8.],
        [4., 7., 9., 2.]]),
 array([[4., 7., 8., 3.],
        [5., 3., 2., 2.]])]

In [75]:
np.hsplit(a,(3,4))

[array([[5., 6., 8.],
        [6., 6., 3.]]),
 array([[6.],
        [8.]]),
 array([[1., 8., 4., 8., 4., 7., 8., 3.],
        [4., 7., 9., 2., 5., 3., 2., 2.]])]

# Menyalin dan menampilkan

In [76]:
a = np.arange(12)
b = a
b is a
b.shape = 3,4
a.shape

(3, 4)

In [77]:
def f(x):
    print(id(x))

In [78]:
id(a)

1852310661680

In [79]:
f(a)

1852310661680


In [80]:
c = a.view()
c is a

False

In [81]:
c.base is a

True

In [84]:
c.flags.owndata

False

In [85]:
c.shape = 2,6
a.shape

(3, 4)

In [86]:
c[0,4] = 1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [88]:
s = a[ : , 1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [89]:
d = a.copy()

In [90]:
d is a

False

In [91]:
d.base is a

False

In [92]:
d[0,0] = 9999

In [93]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

# Aljabar linier

In [96]:
import numpy as np

In [99]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [100]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [101]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [102]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [103]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
np.dot(j, j)

array([[-1.,  0.],
       [ 0., -1.]])

In [104]:
np.trace(u)
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [105]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [109]:
a = np.arange(30)

In [107]:
a.shape = 2,-1,3

In [111]:
a.shape = (2, 5, 3)

In [112]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [113]:
x = np.arange(0,10,2)
y = np.arange(5)
m = np.vstack([x,y])
xy = np.hstack([x,y])